tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true
    php_code_coverage: true
    external_code_coverage: false
checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
build:
    environment:
        mysql: false
        postgresql: false
        redis: false
        php:
            version: 7.4
    dependencies:
        override:
          - composer install --prefer-dist --no-interaction
    tests:
        override:
            - php-scrutinizer-run
            - command: ./vendor/bin/phpunit --coverage-text --coverage-clover=output/clover.txt
              coverage:
                  file: 'clover.txt'
                  format: 'php-clover'
filter:
    excluded_paths: [vendor/*, tests/*]
