# https://travis-ci.com/opensourcewebsite-org/php-telegram-sdk
# https://docs.travis-ci.com
sudo: false
language: php
dist: bionic
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
matrix:
  fast_finish: true
  allow_failures:
    - php: master
install:
  - composer install --prefer-dist --no-interaction
before_script:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=clover.txt
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.composer/vendor
    - vendor
